### ISSUE TITLE
ImportError: ./modules/roi_align/_ext/roi_align/_roi_align.so: undefined symbol: state

### ISSUE THREAD

**Issue by fzh0917** [IlchaeJung/RT-MDNet#14]
I get the following error:
```
Traceback (most recent call last):
  File "Run.py", line 3, in <module>
    from tracker import *
  File "/my_dummy_path/RT-MDNet/tracker.py", line 15, in <module>
    from data_prov import *
  File "./modules/data_prov.py", line 18, in <module>
    from img_cropper import *
  File "./modules/img_cropper.py", line 3, in <module>
    from roi_align.modules.roi_align import RoIAlign
  File "./modules/roi_align/modules/roi_align.py", line 3, in <module>
    from ..functions.roi_align import RoIAlignFunction, RoIAlignAdaFunction, RoIAlignDenseAdaFunction
  File "./modules/roi_align/functions/roi_align.py", line 3, in <module>
    from .._ext import roi_align
  File "./modules/roi_align/_ext/roi_align/__init__.py", line 3, in <module>
    from ._roi_align import lib as _lib, ffi as _ffi
ImportError: ./modules/roi_align/_ext/roi_align/_roi_align.so: undefined symbol: state
```
How to solve it?

**Comment by siyueyu** [comment]
any progress?

**Comment by fzh0917** [comment]
None. I am researching the `SiamRPN` recently.

**Comment by siyueyu** [comment]
okk, thanks a lot.

**Comment by IlchaeJung** [comment]
Thank you for your interest.
I think... it may be a problem related to python version or pytorch version. In my memorial, ffi package is not applicable to python 3.0?.  Could you let me know what version do you use?

**Comment by siyueyu** [comment]
In fact, I found out that it was because that the .so file had not been compiled. It should follow the steps in makefile .

**Comment by fzh0917** [comment]
> Thank you for your interest.
> I think... it may be a problem related to python version or pytorch version. In my memorial, ffi package is not applicable to python 3.0?. Could you let me know what version do you use?

Thanks for your reply. My python version is `3.6.8`.

**Comment by fzh0917** [comment]
> In fact, I found out that it was because that the .so file had not been compiled. It should follow the steps in makefile .

So, should I compile the `.so` file manually ?

**Comment by jimiolaniyan** [comment]
I have also run into this issue. I am  using python `2.7.12`.

**Comment by fzh0917** [comment]
> I have also run into this issue. I am using python `2.7.12`.

So, this is a very interesting problem. @IlchaeJung 
@IlchaeJung Can you reimplement those `C++` code in `Python`? I think that it's a very significant work for all of us. Thanks.

**Comment by siyueyu** [comment]
> > In fact, I found out that it was because that the .so file had not been compiled. It should follow the steps in makefile .
> 
> So, should I compile the `.so` file manually ?

yes, I think so.

**Comment by jimiolaniyan** [comment]
@siyueyu  Kindly share how to compile the `.so` file if you were able to? Thank you

**Comment by siyueyu** [comment]
@jimiolaniyan Have you followed the steps in ./modules/roi_align/makefile. After I do these steps first, this problem solved in my case.

**Comment by jimiolaniyan** [comment]
@siyueyu Not sure how to follow them exactly TBH. If you can share how you did it, that would be helpful. Thank you.

**Comment by siyueyu** [comment]
@jimiolaniyan $ python build.py -> $ make -C src/cuda -> make -C src/cuda clean

**Comment by jimiolaniyan** [comment]
@siyueyu I was able to get past that error. However, i quickly ran into this issue: 

`cudaCheckError() failed : no kernel image is available for execution on the device`

Looks like this is because I have a Tesla K80 gpu. I have tried to recompile the `.so` with `-arch=sm_37` (for K80) but this did not work.

Let me know if you have encountered this and if you have a solution.

**Comment by siyueyu** [comment]
@jimiolaniyan I hadn't met that problem. I am very sorry. But I think that may be caused by cuda version or something about the environment.

**Comment by jimiolaniyan** [comment]
@siyueyu Yes I tried cuda 8.0 but then had a different issue:

`cudaCheckError() failed: invalid device function`

The same issue is reported [here](https://github.com/IlchaeJung/RT-MDNet/issues/2). What is your current set up? 

Also @IlchaeJung I have recompiled the kernel files with `arch=sm_37` (for Tesla K80) but the problem persists. Do you have any guidance on this?

**Comment by siyueyu** [comment]
@jimiolaniyan what about the version of pytorch？

**Comment by jimiolaniyan** [comment]
@siyueyu I have used versions 0.3.0, 0.4.0 and 0.4.1. Which version did you use?

**Comment by IlchaeJung** [comment]
Dear all, 

Sorry, I forgot to mention that recompile of RoIAlign may be need to some other GPU users.
As @siyueyu mentioned, we can recompile RoIAlign layer. 
I used Titan Xp, Titan X maxwell with cuda 8.0 / 9.0, python2.7 and pytorch < 0.4.1. 
I think that users with these settings will be okay after recompiling. However, unfortunately, I do not have an experience with other type of GPU. Moreover, I think that the GPU having memory lower than 10GB should reduce the batch-size for pre-training while it needs at least 2GB~3GB for test. Could you check this memory capacity please?  

To @fzh0917, I really want to extend our code to C++ version. However, it needs some time because I do not familiar with linking c++ to python and  the other project currently I do. But I keep in mind to do that. Thank you.

**Comment by fzh0917** [comment]
@IlchaeJung OK. I quite understand your troubles. Actually, my main purpose is to understand the `RT-MDNet` tracker's core view through reading the corresponding code implementation.

**Comment by jimiolaniyan** [comment]
I was able to get it to work with a P100 GPU on Google cloud. I used:

PyTorch: 0.3.0
Python: 2.7
Cuda: 8.0
