### ISSUE TITLE
Can not display?

### ISSUE THREAD

**Issue by zhulishun** [IlchaeJung/RT-MDNet#28]
when I "python Run.py -visualize",show error

Traceback (most recent call last):
  File "Run.py", line 119, in <module>
    iou_result, result_bb, fps, result_nobb = run_mdnet(img_list, gt[0], gt, seq = seq, display=opts['visualize'])
  File "/home/zhulishun/tracking/RT-MDNet-master/tracker.py", line 422, in run_mdnet
    im = ax.imshow(cur_image, aspect='normal')
  File "/home/zhulishun/anaconda2/envs/rtmdnet/lib/python2.7/site-packages/matplotlib/__init__.py", line 1867, in inner
    return func(ax, *args, **kwargs)
  File "/home/zhulishun/anaconda2/envs/rtmdnet/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 5496, in imshow
    self.set_aspect(aspect)
  File "/home/zhulishun/anaconda2/envs/rtmdnet/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 1373, in set_aspect
    aspect = float(aspect)  # raise ValueError if necessary
ValueError: could not convert string to float: normal

**Comment by JinDouer** [comment]
im = ax.imshow(cur_image, aspect=1)
